### ISSUE TITLE
Fix Importing Static File in Utils.java

### ISSUE THREAD

**Issue by ketanbaitule** [ketanbaitule/WhatsappWithVonage#1]
Something wrong when importing ../static/ + filename. It says file not found.

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at io.openruntimes.java.Server.lambda$execute$0(Server.java:176)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.NoSuchFileException: ../static/index.html
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2923)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3413)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3454)
	at io.openruntimes.java.src.Utils.getStaticFile(Utils.java:20)
	at io.openruntimes.java.src.Main.main(Main.java:13)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 6 more

Return statement missing. return context.res.empty() if no response is expected.
```

**Comment by ketanbaitule** [comment]
Check branch: `static-file-import-issue`

**Comment by ketanbaitule** [comment]
I think the issue lies here

https://github.com/ketanbaitule/WhatsappWithVonage/blob/cfc3d7ce7612be854b14a018ce8ce29811789c7d/src/Utils.java#L17-L22
